### ISSUE TITLE
Release does not take into account the version number from tag

### ISSUE THREAD

**Issue by nalinigans** [GenomicsDB/GenomicsDB-Python#36]
See this [failure](https://github.com/GenomicsDB/GenomicsDB-Python/actions/runs/6907332149). It is because the setup.py has a version set and is not able to take the version from the tag.
Fixes could be something on the lines of `--with-version` being passed to setup.py. See https://github.com/GenomicsDB/GenomicsDB-Python/issues/26 
@mlathara, any other ideas?

**Comment by eneskuluk** [comment]
I didn't try to pass the version from the tag since it was specifying the version in the setup.py. Thought we would increment it after the releases. With something like you mentioned --with-version, it shouldn't be hard to do.

**Comment by nalinigans** [comment]
Yes, the `--with-version` support will be fine, while we look at something  like bump2version mentioned in #26.
